# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('job_salary', models.CharField(max_length=30)),
                ('job_requirement', models.CharField(max_length=2000)),
                ('job_addr', models.CharField(max_length=100)),
                ('job_exp', models.CharField(max_length=20)),
                ('job_edu', models.CharField(max_length=20)),
                ('job_tags', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_employee_num', models.CharField(max_length=20)),
                ('company_type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'jobs info',
            },
        ),
    ]
