# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsinfo',
            name='company_employee_num',
            field=models.CharField(max_length=20),
        ),
    ]
